class TripDayModel {
  const TripDayModel({
    required this.day,
    required this.date,
    required this.morning,
    required this.afternoon,
    required this.evening,
    required this.meals,
    required this.transport,
    required this.estimatedCost,
    required this.estimatedCostValue,
  });

  final int day;
  final String date;
  final String morning;
  final String afternoon;
  final String evening;
  final String meals;
  final String transport;

  // Human-readable value generated by AI.
  final String estimatedCost;

  // Numeric value used for calculations.
  final double estimatedCostValue;

  factory TripDayModel.fromMap(Map<String, dynamic> map) {
    return TripDayModel(
      day: (map['day'] as num?)?.toInt() ?? 1,
      date: map['date']?.toString() ?? '',
      morning: map['morning']?.toString() ?? '',
      afternoon: map['afternoon']?.toString() ?? '',
      evening: map['evening']?.toString() ?? '',
      meals: map['meals']?.toString() ?? '',
      transport: map['transport']?.toString() ?? '',
      estimatedCost: map['estimatedCost']?.toString() ?? '',
      estimatedCostValue: (map['estimatedCostValue'] as num?)?.toDouble() ?? 0,
    );
  }
}

class TripPlanModel {
  const TripPlanModel({
    required this.destination,
    required this.startDate,
    required this.endDate,
    required this.travelers,
    required this.budget,
    required this.interests,
    required this.overview,
    required this.budgetSummary,
    required this.days,
    required this.packingChecklist,
    required this.safetyTips,
    required this.localTips,
  });

  // Basic trip information
  final String destination;
  final DateTime startDate;
  final DateTime endDate;
  final int travelers;

  // Budget and preferences
  final double budget;
  final List<String> interests;

  // AI-generated trip information
  final String overview;
  final String budgetSummary;
  final List<TripDayModel> days;

  // Additional AI recommendations
  final List<String> packingChecklist;
  final List<String> safetyTips;
  final List<String> localTips;
}
