// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUjD8Cc2d3t70lT23YvbFD9o0BJUdD89I',
    appId: '1:308035912254:web:fdfac5933491dd3667076f',
    messagingSenderId: '308035912254',
    projectId: 'voyara-38487',
    authDomain: 'voyara-38487.firebaseapp.com',
    storageBucket: 'voyara-38487.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLc4JPFQlxA01pqE340AW5Mr97PWTQTv8',
    appId: '1:308035912254:android:a322ebc5ba0f341067076f',
    messagingSenderId: '308035912254',
    projectId: 'voyara-38487',
    storageBucket: 'voyara-38487.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsdUPppTQwQooExnUXQn-afoVUMBV8Dvo',
    appId: '1:308035912254:ios:15d8327b43d7bd4667076f',
    messagingSenderId: '308035912254',
    projectId: 'voyara-38487',
    storageBucket: 'voyara-38487.firebasestorage.app',
    androidClientId: '308035912254-fedu35vkd1pv0b2f6fa235srfqpn1sv8.apps.googleusercontent.com',
    iosClientId: '308035912254-3j263i9388o278qu0n7dlnob3i2gst56.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsdUPppTQwQooExnUXQn-afoVUMBV8Dvo',
    appId: '1:308035912254:ios:15d8327b43d7bd4667076f',
    messagingSenderId: '308035912254',
    projectId: 'voyara-38487',
    storageBucket: 'voyara-38487.firebasestorage.app',
    androidClientId: '308035912254-fedu35vkd1pv0b2f6fa235srfqpn1sv8.apps.googleusercontent.com',
    iosClientId: '308035912254-3j263i9388o278qu0n7dlnob3i2gst56.apps.googleusercontent.com',
    iosBundleId: 'com.example.voyara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUjD8Cc2d3t70lT23YvbFD9o0BJUdD89I',
    appId: '1:308035912254:web:7a361c3ff3d50fd367076f',
    messagingSenderId: '308035912254',
    projectId: 'voyara-38487',
    authDomain: 'voyara-38487.firebaseapp.com',
    storageBucket: 'voyara-38487.firebasestorage.app',
  );
}
